defaults: &defaults
    collection_local_id:
        'alexharris':
            controller: digital_collections
            collection: alexharris
            item_id_field: local_id
            thumbnail_image: "ahpst001024"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
