collection_local_id:
  uamensbasketballposters:
    controller: digital_collections
    collection: uamensbasketballposters
    item_id_field: local_id
    thumbnail_image:
      local_id: dbpst002001
