defaults: &defaults
    includes:
        admin_policy_pids:
            - 'changeme:330'
    showcase_images:
        - "changeme:333"
        - "changeme:336"
    highlight_images:
        - "changeme:337"
        - "changeme:343"
        - "changeme:340"
        - "changeme:342"
    blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=wdukesons
    alert: 'Welcome to the W. Duke & Sons collection - the first to appear in the next-generation platform we’re developing for Duke Digital Collections. <a href="http://blogs.library.duke.edu/bitstreams/2015/10/22/today-is-the-new-future-tripod3/">More about the project &raquo;</a>'
    configure_blacklight:
        add_facet_fields:
          - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
            label: Browse
            show: false
          - field: "Ddr::Index::Fields::SERIES_FACET"
            label: Card Series
            collapse: false
            limit: 5
          - field: "Ddr::Index::Fields::YEAR_FACET"
            label: Year
            limit: 9999
            collapse: false
            range:
                num_segments: 6
                segments: true
          - field: "Ddr::Index::Fields::TYPE_FACET"
            label: Type
            limit: 5
          - field: "Ddr::Index::Fields::PUBLISHER_FACET"
            label: Publisher
            limit: 5
          - field: "Ddr::Index::Fields::SPATIAL_FACET"
            label: Location
            limit: 5
          - field: "Ddr::Index::Fields::BOX_NUMBER_FACET"
            label: Box Number
            limit: 5
            sort: index
        add_show_fields:
          - field: "ActiveFedora::SolrService.solr_name(:title, :stored_searchable)"
            separator: "; "
            label: "Title"
          - field: "Ddr::Index::Fields::PERMANENT_URL"
            label: "Permalink"
            helper_method: permalink
          - field: "Ddr::Index::Fields::IS_PART_OF"
            label: "Part of"
            helper_method: descendant_of
          - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
            label: "Collection"
            helper_method: descendant_of
          - field: "ActiveFedora::SolrService.solr_name(:series, :stored_searchable)"
            separator: "; "
            label: "Card Series"
            link_to_search: "Ddr::Index::Fields::SERIES_FACET"
          - field: "ActiveFedora::SolrService.solr_name(:type, :stored_searchable)"
            separator: "; "
            label: "Type"
            link_to_search: "Ddr::Index::Fields::TYPE_FACET"
          - field: "ActiveFedora::SolrService.solr_name(:spatial, :stored_searchable)"
            separator: "; "
            label: "Location"
            link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
          - field: "ActiveFedora::SolrService.solr_name(:publisher, :stored_searchable)"
            separator: "; "
            label: "Publisher"
            link_to_search: "Ddr::Index::Fields::PUBLISHER_FACET"
          - field: "ActiveFedora::SolrService.solr_name(:date, :stored_searchable)"
            separator: "; "
            label: "Year"
            helper_method: year_ranges
          - field: "ActiveFedora::SolrService.solr_name(:language, :stored_searchable)"
            separator: "; "
            label: "Language"
            helper_method: language_display
          - field: "Ddr::Index::Fields::EAD_ID"
            separator: "; "
            label: "Source Collection"
            helper_method: source_collection
          - field: "ActiveFedora::SolrService.solr_name(:box_number, :stored_searchable)"
            separator: "; "
            label: "Box Number"
          - field: "ActiveFedora::SolrService.solr_name(:extent, :stored_searchable)"
            separator: "; "
            label: "Extent"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  