includes:
  admin_sets:
    - dc
showcase_images:
  local_ids:
    - 1092513-R4-E402
    - 19310417WC0422
    - 19310417WC0424
    - ahpst001015
    - ahpst001024
    - ahpst002028
    - brpst002001
    - brpst008001
    - CK0029
    - csmep03156
    - dscsi03033
    - dscsi05004
    - dscsi05008
    - fcpst001001026
    - gmpph010020020
    - gmpph040010050
    - hmpgp13344
    - hmpgp19570
    - kfpst0040070010
    - kfpst0040190010
    - MM1134
    - Q0012
    - rrpph05001002
    - rrpph06002009
  layout: landscape
highlight_images:
  local_ids:
    - 1092513-R3-E311
    - 1092531-R3-E448
    - 19290402WC0185
    - 19300205WC0310
    - 19310417WC0425
    - A0128
    - A0324
    - ahpst001024
    - ahpst002005
    - ahpst002026
    - ahpst002028
    - BH0904
    - BH1939
    - brpst008001
    - CK0036
    - csmep03116
    - D0308
    - dscsi02551
    - dscsi03002
    - dscsi03005
    - dscsi03268
    - dscsi03304
    - espst001002
    - espst001004
    - espst001016
    - esrph080013590
    - gmpph010020130
    - gmpph010020150
    - hmpgp12331
    - hmpgp14408
    - hmpgp21657
    - hmpgp22673
    - japph030030010
    - japph030060010
    - japph040280010
    - kfpst0060050010
    - kfpst0060070010
    - mfb042
    - mfb075
    - mfb099
    - mfb109
    - MM0190
    - MM0298
    - rrpph01001017
    - rrpph01002001
    - rrpph02001014
    - strst001001059
    - strst001001110
    - strst001001143
    - T2415
featured_collections:
  local_ids:
    - adaccess
    - rushbenjaminandjulia
    - alexharris
    - dukechapel
    - karales
    - eaa
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_posts/
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::SERIES_FACET"
      label: Series
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::LANGUAGE_FACET"
      label: Language
      limit: 5
    - field: "Ddr::Index::Fields::SPATIAL_FACET"
      label: Location
      limit: 5
    - field: "Ddr::Index::Fields::CREATOR_FACET"
      label: Creator
      limit: 5
    - field: "Ddr::Index::Fields::PUBLICATION_FACET"
      label: Publication
      limit: 5
    - field: "Ddr::Index::Fields::COLLECTION_TITLE"
      label: Collection
      limit: 5
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::BOX_NUMBER_FACET"
      label: "Box Number"
      show: false
    - field: "Ddr::Index::Fields::CONTRIBUTOR_FACET"
      label: Contributor
      limit: 5
      show: false
    - field: "Ddr::Index::Fields::ASPACE_ID"
      label: ArchivesSpace ID
      show: false

  add_index_field:
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: "permalink"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
  add_show_field:
    - field: "Ddr::Index::Fields::MEDIA_TYPE"
      label: "File"
      helper_method: file_info
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :alternative
        - :stored_searchable
      separator: "; "
      label: "Alternative Title"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
      link_to_search: "Ddr::Index::Fields::CREATOR_FACET"
    - field:
        - :contributor
        - :stored_searchable
      separator: "; "
      label: "Contributor"
      link_to_search: "Ddr::Index::Fields::CONTRIBUTOR_FACET"
    - field:
        - :description
        - :stored_searchable
      label: Description
      helper_method: simple_format_values
    - field:
        - :spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :publisher
        - :stored_searchable
      separator: "; "
      label: "Publisher"
    - field:
        - :publication
        - :stored_searchable
      separator: "; "
      label: "Publication"
      link_to_search: "Ddr::Index::Fields::PUBLICATION_FACET"
    - field:
        - :language_name
        - :stored_searchable
      separator: "; "
      label: "Language"
      link_to_search: "Ddr::Index::Fields::LANGUAGE_FACET"
    - field:
        - :extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :series
        - :stored_searchable
      separator: "; "
      label: "Series"
      link_to_search: "Ddr::Index::Fields::SERIES_FACET"
    - field:
        - :subseries
        - :stored_searchable
      separator: "; "
      label: "Subseries"
      link_to_search: "Ddr::Index::Fields::SUBSERIES_FACET"
    - field:
        - :box_number
        - :stored_searchable
      separator: "; "
      label: "Box Number"
      link_to_search: "Ddr::Index::Fields::BOX_NUMBER_FACET"
    - field:
        - :folder
        - :stored_searchable
      separator: "; "
      label: "Folder"
    - field:
        - :print_number
        - :stored_searchable
      separator: "; "
      label: "Print Number"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: "Rights"
      helper_method: "rights_display"
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
      helper_method: :auto_link_values
    - field:
        - :hasVersion
        - :stored_searchable
      separator: "; "
      label: "Other Version"
      helper_method: :auto_link_values
    - field: "Ddr::Index::Fields::IDENTIFIER_ALL"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field: 'sponsor_display'
      separator: "; "
      label: "Sponsor"
      accessor: 'sponsor_display'
      helper_method: collection_sponsor
