defaults: &defaults
    admin_sets:
        'dc':
            controller: digital_collections
            item_id_field: id
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  