includes:
  admin_sets:
    - dc
showcase_images:
  local_ids:
    - 1092513-R4-E402
    - 19310417WC0422
    - 19310417WC0424
    - ahpst001015
    - ahpst001024
    - ahpst002028
    - brpst002001
    - brpst008001
    - csmep03156
    - dscsi03033
    - dscsi05004
    - dscsi05008
    - fcpst001001026
    - gmpph010020020
    - gmpph040010050
    - hmpgp13344
    - hmpgp19570
    - kfpst0040070010
    - kfpst0040190010
    - rrpph05001002
    - rrpph06002009
  layout: landscape
highlight_images:
  local_ids:
    - 1092513-R3-E311
    - 1092531-R3-E448
    - 19290402WC0185
    - 19300205WC0310
    - 19310417WC0425
    - ahpst001024
    - ahpst002005
    - ahpst002026
    - ahpst002028
    - brpst008001
    - csmep03116
    - dscsi02551
    - dscsi03002
    - dscsi03005
    - dscsi03268
    - dscsi03304
    - espst001002
    - espst001004
    - espst001016
    - esrph080013590
    - gmpph010020130
    - gmpph010020150
    - hmpgp12331
    - hmpgp14408
    - hmpgp21657
    - hmpgp22673
    - japph030030010
    - japph030060010
    - japph040280010
    - kfpst0060050010
    - kfpst0060070010
    - mfb042
    - mfb075
    - mfb099
    - mfb109
    - rrpph01001017
    - rrpph01002001
    - rrpph02001014
    - strst001001059
    - strst001001110
    - strst001001143
featured_collections:
  local_ids:
    - wdukesons
    - rushbenjaminandjulia
    - alexharris
    - dukechapel
    - karales
    - hmp
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_posts/
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::SERIES_FACET"
      label: Series
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::SPATIAL_FACET"
      label: Location
      limit: 5
    - field: "Ddr::Index::Fields::CREATOR_FACET"
      label: Creator
      limit: 5
    - field: "Ddr::Index::Fields::COLLECTION_FACET"
      label: 'Collection'
      helper_method: 'collection_title'
      limit: 5
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
  add_index_field:
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: "permalink"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
  add_show_field:
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
      link_to_search: "Ddr::Index::Fields::CREATOR_FACET"
    - field:
        - :description
        - :stored_searchable
      helper_method: separate_with_p
      label: Description
    - field: "Ddr::Index::Fields::LOCAL_ID"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field:
        - :series
        - :stored_searchable
      separator: "; "
      label: "Series"
      link_to_search: "Ddr::Index::Fields::SERIES_FACET"
    - field:
        - :sub_series
        - :stored_searchable
      separator: "; "
      label: "Sub Series"
    - field:
        - :box_number
        - :stored_searchable
      separator: "; "
      label: "Box Number"
      link_to_search: "Ddr::Index::Fields::BOX_NUMBER_FACET"
    - field:
        - :folder
        - :stored_searchable
      separator: "; "
      label: "Folder"
    - field:
        - :print_number
        - :stored_searchable
      separator: "; "
      label: "Print Number"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: Rights
