defaults: &defaults
    includes:
        admin_sets:
            - dc
    configure_blacklight:
        add_facet_fields:
          - field: "Ddr::Index::Fields::COLLECTION_FACET"
            label: 'Collection'
            helper_method: 'collection_title'
            limit: 9999
            collapse: false
          - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
            label: Browse
            show: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  