includes:
  admin_sets:
    - dvs
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::COLLECTION_TITLE"
      label: 'Collection'
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::TYPE_FACET"
      label: Type
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::CREATOR_FACET"
      label: Creator
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
  add_index_field:
    - field: "Ddr::Index::Fields::MEDIA_TYPE"
      label: "File"
      helper_method: file_info
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
    - field:
        - :type
        - :stored_searchable
      separator: "; "
      label: "Type"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: descendant_of
  add_show_field:
    - field: "Ddr::Index::Fields::MEDIA_TYPE"
      label: "File"
      helper_method: file_info
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
      link_to_search: "Ddr::Index::Fields::CREATOR_FACET"
    - field:
        - :type
        - :stored_searchable
      separator: "; "
      label: "Type"
    - field:
        - :description
        - :stored_searchable
      separator: "; "
      label: Description
    - field: "Ddr::Index::Fields::IDENTIFIER_ALL"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :relation
        - :stored_searchable
      label: "More Information"
      separator: "; "
      helper_method: "auto_link_values"
    - field:
        - :spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: "Rights"
      helper_method: "rights_display"
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
      helper_method: :auto_link_values
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field:
        - :sponsor
        - :stored_searchable
      separator: "; "
      label: "Sponsor"
