collection_local_id:
  valentinejackson:
    controller: digital_collections
    collection: valentinejackson
    item_id_field: local_id
    thumbnail_image:
      custom_image: valentinejackson-thumb-1837-11-01-p1.jpg
