collection_local_id:
  haitideclaration:
    controller: digital_collections
    collection: haitideclaration
    item_id_field: local_id
    thumbnail_image:
      custom_image: haitideclaration-thumb-hdims01001.jpg
