includes:
  local_ids:
    - mma
showcase_images:
  local_ids:
    - MM0189
    - MM0596
    - MM0567
    - MM0406
    - MM0169
    - MM0468
    - MM0337
    - MM0190
    - MM0581
  layout: portrait
highlight_images:
  local_ids:
    - MM0444
    - MM0298
    - MM0462
    - MM0700
    - MM0617
    - MM0447
    - MM0483
    - MM0169
    - MM0731
    - MM0673
    - MM0571
    - MM0238
    - MM0720
    - MM1134
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=mma
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::COMPANY_FACET"
      label: Company
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::PRODUCT_FACET"
      label: Product
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::PUBLICATION_FACET"
      label: Publication
      limit: 5
    - field: "Ddr::Index::Fields::MEDIUM_FACET"
      label: Medium
      limit: 5
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5

  add_show_field:
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :headline
        - :stored_searchable
      label: "Headline"
      helper_method: separate_with_p
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :description
        - :stored_searchable
      label: "Description"
      helper_method: separate_with_p
    - field:
        - :company
        - :stored_searchable
      separator: "; "
      label: "Company"
      link_to_search: "Ddr::Index::Fields::COMPANY_FACET"
    - field:
        - :product
        - :stored_searchable
      separator: "; "
      label: "Product"
      link_to_search: "Ddr::Index::Fields::PRODUCT_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :publication
        - :stored_searchable
      separator: "; "
      label: "Publication"
      link_to_search: "Ddr::Index::Fields::PUBLICATION_FACET"
    - field:
        - :medium
        - :stored_searchable
      separator: "; "
      label: "Medium"
      link_to_search: "Ddr::Index::Fields::MEDIUM_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :type
        - :stored_searchable
      separator: "; "
      label: "Type"
      link_to_search: "Ddr::Index::Fields::TYPE_FACET"
    - field:
        - :artist
        - :stored_searchable
      separator: "; "
      label: "Artist"
    - field:
        - :language
        - :stored_searchable
      separator: "; "
      label: "Language"
      helper_method: language_display
    - field:
        - :extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: Rights
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field: "Ddr::Index::Fields::LOCAL_ID"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink

  add_index_field:
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :company
        - :stored_searchable
      separator: "; "
      label: "Company"
      link_to_search: "Ddr::Index::Fields::COMPANY_FACET"
    - field:
        - :product
        - :stored_searchable
      separator: "; "
      label: "Product"
      link_to_search: "Ddr::Index::Fields::PRODUCT_FACET"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
