collection_local_id:
  spauldingbryant:
    controller: digital_collections
    collection: spauldingbryant
    item_id_field: local_id
    thumbnail_image:
      custom_image: spauldingbryant-thumb-1873-08-16-p01.jpg
