defaults: &defaults
    collection_local_id:
        'hmp':
            controller: digital_collections
            collection: hmp
            item_id_field: local_id
            thumbnail_image: "hmpgp12314"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
