defaults: &defaults
    collection_local_id:
        'rushbenjaminandjulia':
            controller: digital_collections
            collection: rushbenjaminandjulia
            item_id_field: local_id
            thumbnail_image: "brpst031001"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
