collection_local_id:
  dukechronicle:
    controller: digital_collections
    collection: dukechronicle
    item_id_field: local_id
    thumbnail_image:
      custom_image: dukechronicle-thumb-dchnp34011.jpg
