includes:
  local_ids:
    - eaa
showcase_images:
  local_ids:
    - A0128
    - CK0029
    - CK0036
    - CK0067
    - D0308
    - D0369
    - J0013
    - J0102
    - K0076
    - K0266
    - P0093
  layout: portrait
highlight_images:
  local_ids:
    - A0163
    - A0324
    - A0426
    - A0449
    - A0499
    - A0677
    - B0172
    - CK0010
    - CK0047
    - CK0048
    - J0049
    - K0207
    - M0138
    - P0048
    - P0091
    - Q0012
    - Q0047
    - Q0050
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=eaa
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::COMPANY_FACET"
      label: Company
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::PRODUCT_FACET"
      label: Product
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::CATEGORY_FACET"
      label: Category
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::SPATIAL_FACET"
      label: Location
      limit: 5
    - field: "Ddr::Index::Fields::PUBLICATION_FACET"
      label: Publication
      limit: 5
    - field: "Ddr::Index::Fields::MEDIUM_FACET"
      label: Medium
      limit: 5
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::TYPE_FACET"
      label: Type
      show: false

  add_show_field:
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :headline
        - :stored_searchable
      label: "Headline"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :description
        - :stored_searchable
      label: "Description"
    - field:
        - :company
        - :stored_searchable
      separator: "; "
      label: "Company"
      link_to_search: "Ddr::Index::Fields::COMPANY_FACET"
    - field:
        - :product
        - :stored_searchable
      separator: "; "
      label: "Product"
      link_to_search: "Ddr::Index::Fields::PRODUCT_FACET"
    - field:
        - :category
        - :stored_searchable
      separator: "; "
      label: "Category"
      link_to_search: "Ddr::Index::Fields::CATEGORY_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :publication
        - :stored_searchable
      separator: "; "
      label: "Publication"
      link_to_search: "Ddr::Index::Fields::PUBLICATION_FACET"
    - field:
        - :medium
        - :stored_searchable
      separator: "; "
      label: "Medium"
      link_to_search: "Ddr::Index::Fields::MEDIUM_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :type
        - :stored_searchable
      separator: "; "
      label: "Type"
      link_to_search: "Ddr::Index::Fields::TYPE_FACET"
    - field:
        - :artist
        - :stored_searchable
      separator: "; "
      label: "Artist"
    - field:
        - :language
        - :stored_searchable
      separator: "; "
      label: "Language"
      helper_method: language_display
    - field:
        - :extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: Rights
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field: "Ddr::Index::Fields::LOCAL_ID"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field: 'sponsor_display'
      separator: "; "
      label: "Sponsor"
      accessor: 'sponsor_display'
      helper_method: collection_sponsor

  add_index_field:
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :company
        - :stored_searchable
      separator: "; "
      label: "Company"
      link_to_search: "Ddr::Index::Fields::COMPANY_FACET"
    - field:
        - :product
        - :stored_searchable
      separator: "; "
      label: "Product"
      link_to_search: "Ddr::Index::Fields::PRODUCT_FACET"
    - field:
        - :category
        - :stored_searchable
      separator: "; "
      label: "Category"
      link_to_search: "Ddr::Index::Fields::CATEGORY_FACET"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
