defaults: &defaults
  configure_blacklight:
      add_facet_field:
        - field: "Ddr::Index::Fields::ADMIN_SET_FACET"
          label: Collection Group
          helper_method: admin_set_full_name
          collapse: false
          limit: 5
        - field: "Ddr::Index::Fields::COLLECTION_FACET"
          label: Collection
          helper_method: collection_title
          limit: 5
        - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
          label: Browse
          show: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
