includes:
  local_ids:
    - esr
showcase_images:
  local_ids:
    - esrph020010580
    - esrph080014320
    - esrph080014720
    - esrph080014880
    - esrph090015610
    - esrph090015910
    - esrph100016700
  layout: landscape
highlight_images:
  local_ids:
    - esrph020010400
    - esrph040011070
    - esrph040011110
    - esrph040011560
    - esrph040012110
    - esrph040012380
    - esrph080013390
    - esrph080013590
    - esrph080014830
    - esrph080014960
    - esrph090015740
    - esrph090015830
    - esrph090015840
    - esrsc120010550
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=esr
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::SERIES_FACET"
      label: Series
      limit: 5
    - field: "Ddr::Index::Fields::SPATIAL_FACET"
      label: Location
      limit: 5
    - field: "Ddr::Index::Fields::CREATOR_FACET"
      label: Creator
      limit: 5
    - field: "Ddr::Index::Fields::EAD_ID"
      label: "Source Collection"
      limit: 5
      helper_method: 'ead_id_title'
  add_index_field:
    - field:
        - :dc_creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
    - field:
        - :dc_date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :dc_format
        - :stored_searchable
      separator: ";"
      label: "Format"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: "permalink"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
  add_show_field:
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :dc_date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :dc_creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
      link_to_search: "Ddr::Index::Fields::CREATOR_FACET"
    - field:
        - :dc_description
        - :stored_searchable
      separator: "; "
      label: Description
    - field: "Ddr::Index::Fields::LOCAL_ID"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :dc_spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :dc_subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :dc_format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :dc_extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field:
        - :duketerms_series
        - :stored_searchable
      separator: "; "
      label: "Series"
      link_to_search: "Ddr::Index::Fields::SERIES_FACET"
    - field:
        - :duketerms_sub_series
        - :stored_searchable
      separator: "; "
      label: "Sub Series"
    - field:
        - :duketerms_box_number
        - :stored_searchable
      separator: "; "
      label: "Box Number"
      link_to_search: "Ddr::Index::Fields::BOX_NUMBER_FACET"
    - field:
        - :duketerms_folder
        - :stored_searchable
      separator: "; "
      label: "Folder"
    - field:
        - :duketerms_print_number
        - :stored_searchable
      separator: "; "
      label: "Print Number"
    - field:
        - :dc_provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
    - field:
        - :dc_rights
        - :stored_searchable
      separator: "; "
      label: Rights
