includes:
  local_ids:
    - caribbeansea
showcase_images:
  local_ids:
    - csmep02010
    - csmep02011
    - csmep02013
    - csmep03116
    - csmep03156
  layout: landscape
highlight_images:
  local_ids:
    - csmep01004
    - csmep02026
    - csmep02060
    - csmep02113
    - csmep02120
    - csmep03160
    - csmep03164
    - csmep03179
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=caribbeansea
