includes:
  local_ids:
    - museedeshorreurs
showcase_images:
  local_ids:
    - mdhps01001010
    - mdhps01001012
    - mdhps01001019
    - mdhps01001020
    - mdhps01001038
    - mdhps01001050
  layout: portrait
highlight_images:
  local_ids:
    - mdhps01001007
    - mdhps01001013
    - mdhps01001025
    - mdhps01001033
    - mdhps01001034
    - mdhps01001040
    - mdhps01001048
    - mdhps01001054
    - mdhps01001055
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=museedeshorreurs
