includes:
  local_ids:
    - ronaldreis
showcase_images:
  local_ids:
    - rrpph01001015
    - rrpph01001017
    - rrpph01002001
    - rrpph02001014
    - rrpph04003013
    - rrpph05001002
    - rrpph05002008
    - rrpph06002009
  layout: landscape
highlight_images:
  local_ids:
    - rrpph01002008
    - rrpph01004007
    - rrpph02002014
    - rrpph03002006
    - rrpph04002007
    - rrpph05001007
    - rrpph06001010
restrictions:
  max_download: 1200
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=ronaldreis
