collection_local_id:
  brownfrankclyde:
    controller: digital_collections
    collection: brownfrankclyde
    item_id_field: local_id
    thumbnail_image:
      custom_image: brownfrankclyde-thumb-all-day-singing.jpg
