includes:
  local_ids:
    - gamble
showcase_images:
  local_ids:
    - gamble_020A_103
    - gamble_047B_0498
    - gamble_053B_0571
    - gamble_214A_1192
    - gamble_242A_1360
    - gamble_243A_1365A
    - gamble_515A_2981
    - RL_10074_LS_0056
    - RL_10074_LS_0141
    - RL_10074_LS_0197
    - RL_10074_LS_0334
    - RL_10074_LS_0342
  layout: landscape
highlight_images:
  local_ids:
    - gamble_047B_0503
    - gamble_047B_0504
    - gamble_054B_0583
    - gamble_125A_705
    - gamble_132A_744
    - gamble_138A_776
    - gamble_139A_786
    - gamble_140A_788
    - gamble_171A_963
    - gamble_244A_1373
    - gamble_258A_1474
    - gamble_285A_1630
    - gamble_294A_1682
    - gamble_362A_2070
    - gamble_396A_2274A
    - gamble_445A_2564
    - gamble_512A_2962
    - gamble_russia_0055
    - RL_10074_LS_0040
    - RL_10074_LS_0047
    - RL_10074_LS_0081
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=gamble

item_relators:
  - name: "Individual Photographs"
    field:
      - :hasPart
      - :stored_searchable
    id_field:
      - :permanent_id
      - :stored_sortable
  - name: "Photograph Album"
    field:
      - :isPartOf
      - :stored_searchable
    id_field:
      - :permanent_id
      - :stored_sortable
  - name: "Related Items"
    field:
      - :hasVersion
      - :stored_searchable
    id_field:
      - :permanent_id
      - :stored_sortable
  - name: "Related Items"
    field:
      - :isVersionOf
      - :stored_searchable
    id_field:
      - :permanent_id
      - :stored_sortable

configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::SERIES_FACET"
      label: Series
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::LANGUAGE_FACET"
      label: Language
      limit: 5
    - field: "Ddr::Index::Fields::SPATIAL_FACET"
      label: Location
      limit: 5
    - field: "Ddr::Index::Fields::CREATOR_FACET"
      label: Creator
      limit: 5
    - field: "Ddr::Index::Fields::PUBLICATION_FACET"
      label: Publication
      limit: 5
    - field: "Ddr::Index::Fields::COLLECTION_TITLE"
      label: Collection
      limit: 5
    - field: "Ddr::Index::Fields::COMMON_MODEL_NAME"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::BOX_NUMBER_FACET"
      label: "Box Number"
      show: false
    - field: "Ddr::Index::Fields::CONTRIBUTOR_FACET"
      label: Contributor
      limit: 5
      show: false
    - field: "Ddr::Index::Fields::ASPACE_ID"
      label: ArchivesSpace ID
      show: false
    - field: "Ddr::Index::Fields::CATEGORY_FACET"
      label: Category
      show: false

  add_index_field:
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :temporal
        - :stored_searchable
      separator: "; "
      label: "Temporal"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: "permalink"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
  add_show_field:
    - field: "Ddr::Index::Fields::MEDIA_TYPE"
      label: "File"
      helper_method: file_info
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :alternative
        - :stored_searchable
      separator: "; "
      label: "Alternative Title"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
      link_to_search: "Ddr::Index::Fields::CREATOR_FACET"
    - field:
        - :contributor
        - :stored_searchable
      separator: "; "
      label: "Contributor"
      link_to_search: "Ddr::Index::Fields::CONTRIBUTOR_FACET"
    - field:
        - :description
        - :stored_searchable
      label: Description
      helper_method: simple_format_and_auto_link_values
    - field:
        - :spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :publisher
        - :stored_searchable
      separator: "; "
      label: "Publisher"
    - field:
        - :publication
        - :stored_searchable
      separator: "; "
      label: "Publication"
      link_to_search: "Ddr::Index::Fields::PUBLICATION_FACET"
    - field:
        - :language_name
        - :stored_searchable
      separator: "; "
      label: "Language"
      link_to_search: "Ddr::Index::Fields::LANGUAGE_FACET"
    - field:
        - :extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :series
        - :stored_searchable
      separator: "; "
      label: "Series"
      link_to_search: "Ddr::Index::Fields::SERIES_FACET"
    - field:
        - :subseries
        - :stored_searchable
      separator: "; "
      label: "Subseries"
      link_to_search: "Ddr::Index::Fields::SUBSERIES_FACET"
    - field:
        - :box_number
        - :stored_searchable
      separator: "; "
      label: "Box Number"
      link_to_search: "Ddr::Index::Fields::BOX_NUMBER_FACET"
    - field:
        - :folder
        - :stored_searchable
      separator: "; "
      label: "Folder"
    - field:
        - :print_number
        - :stored_searchable
      separator: "; "
      label: "Print Number"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
      helper_method: :auto_link_values
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: "Rights"
      helper_method: "rights_display"
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
      helper_method: :auto_link_values
    - field:
        - :hasVersion
        - :stored_searchable
      separator: "; "
      label: "Other Version"
      helper_method: :auto_link_values
    - field: "Ddr::Index::Fields::IDENTIFIER_ALL"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field: "Ddr::Index::Fields::DOI"
      label: "DOI"
      helper_method: link_to_doi
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field: 'sponsor_display'
      separator: "; "
      label: "Sponsor"
      accessor: 'sponsor_display'
      helper_method: collection_sponsor
