defaults: &defaults
    admin_sets:
        'nescent':
            controller: catalog
            item_id_field: id
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  