defaults: &defaults
    collection_local_id:
        'blake':
            controller: digital_collections
            collection: blake
            item_id_field: local_id
            thumbnail_image: "mfb001"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
