collection_local_id:
  jwtnewsletters:
    controller: digital_collections
    collection: jwtnewsletters
    item_id_field: local_id
    thumbnail_image:
      custom_image: jwtnewsletters-thumb-jwtnl13039.jpg
