defaults: &defaults
    includes:
        local_ids:
           - 'dukechapel'
    showcase_images:
      custom_images:
        - dukechapel-causeway.jpg
        - dukechapel-grainy.jpg
      layout: landscape
    blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=dukechapel
    configure_blacklight:
        add_facet_field:
          - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
            label: Browse
            show: false

        add_show_field:
          - field: "Ddr::Index::Fields::TITLE"
            separator: "; "
            label: "Title"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults