includes:
  local_ids:
    - dukechapel
showcase_images:
  custom_images:
    - dukechapel-causeway.jpg
    - dukechapel-grainy.jpg
  layout: landscape
show_items: 0
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=dukechapel
item_relators:
  - name: "Related Item"
    field:
      - :relation
      - :stored_searchable
    id_field:
      - :permanent_id
      - :stored_sortable
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::CREATOR_FACET"
      label: Speaker
      sort: index
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::CATEGORY_FACET"
      label: "Liturgical Calendar"
      sort: index
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::BIBLICAL_BOOK_FACET"
      label: "Biblical Book"
      sort: index
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::CHAPTER_AND_VERSE_FACET"
      label: "Chapter and Verse"
      sort: index
      collapse: true
      limit: 5
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      sort: index
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: "Format"
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::EAD_ID"
      label: "Source Collection"
      limit: 5
      helper_method: 'ead_id_title'

  add_show_field:
    - field: "Ddr::Index::Fields::MEDIA_TYPE"
      label: "File"
      helper_method: file_info
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :description
        - :stored_searchable
      label: Description
      helper_method: simple_format_and_auto_link_values
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Speaker"
      link_to_search: "Ddr::Index::Fields::CREATOR_FACET"
    - field:
        - :category
        - :stored_searchable
      label: "Liturgical Calendar"
      link_to_search: "Ddr::Index::Fields::CATEGORY_FACET"
    - field:
        - :biblical_book
        - :stored_searchable
      label: "Biblical Book"
      link_to_search: "Ddr::Index::Fields::BIBLICAL_BOOK_FACET"
    - field:
        - :chapter_and_verse
        - :stored_searchable
      label: "Chapter and Verse"
      link_to_search: "Ddr::Index::Fields::CHAPTER_AND_VERSE_FACET"
    - field:
        - :subject
        - :stored_searchable
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :contributor
        - :stored_searchable
      separator: "; "
      label: "Contributor"
    - field: "Ddr::Index::Fields::IDENTIFIER_ALL"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :language_name
        - :stored_searchable
      separator: "; "
      label: "Language"
    - field:
        - :spatial
        - :stored_searchable
      label: "Location"
    - field:
        - :format
        - :stored_searchable
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
      helper_method: :auto_link_values
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: "Rights"
      helper_method: "rights_display"
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
      helper_method: :auto_link_values
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field: 'sponsor_display'
      separator: "; "
      label: "Sponsor"
      accessor: 'sponsor_display'
      helper_method: collection_sponsor

  add_index_field:
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Speaker"
      link_to_search: "Ddr::Index::Fields::CREATOR_FACET"
    - field:
        - :category
        - :stored_searchable
      separator: "; "
      label: "Liturgical Calendar"
      link_to_search: "Ddr::Index::Fields::CATEGORY_FACET"
    - field:
        - :biblical_book
        - :stored_searchable
      separator: "; "
      label: "Biblical Book"
      link_to_search: "Ddr::Index::Fields::BIBLICAL_BOOK_FACET"
    - field:
        - :chapter_and_verse
        - :stored_searchable
      label: "Chapter and Verse"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
