collection_local_id:
  dukengineer:
    controller: digital_collections
    collection: dukengineer
    item_id_field: local_id
    thumbnail_image:
      custom_image: dukengineer-thumb-denms260040010.jpg
