includes:
  local_ids:
    - jwtfordmotorads
showcase_images:
  local_ids:
    - jwtad010020010
    - jwtad440020170
    - jwtad440090150
    - jwtad530060020
    - jwtad160060110
    - jwtad230030070
    - jwtad320070010
    - jwtad370020010
    - jwtad390040070
    - jwtad020011070
    - jwtad250130110
  layout: portrait
highlight_images:
  local_ids:
    - jwtad190030090
    - jwtad370030010
    - jwtad550190030
    - jwtad250050020
    - jwtad300030050
    - jwtad370030040
    - jwtad010020030
    - jwtad100040090
    - jwtad390160210
    - jwtad420010030
    - jwtad480010150
    - jwtad490010310
    - jwtad060010160
    - jwtad160020120
    - jwtad320050080
    - jwtad220010130
    - jwtad350010960
    - jwtad460010040
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=jwtfordmotorads
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::PRODUCT_FACET"
      label: Product
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::CATEGORY_FACET"
      label: Vehicle Category
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
    - field: "Ddr::Index::Fields::SETTING_FACET"
      label: Setting
      limit: 5
    - field: "Ddr::Index::Fields::LANGUAGE_FACET"
      label: Language
      limit: 5
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::BOX_NUMBER_FACET"
      label: "Box Number"
      show: false
    - field: "Ddr::Index::Fields::TYPE_FACET"
      label: Type
      show: false
    - field: "Ddr::Index::Fields::FOLDER_FACET"
      label: Folder
      show: false


  add_show_field:
    - field: "Ddr::Index::Fields::MEDIA_TYPE"
      label: "File"
      helper_method: file_info
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :description
        - :stored_searchable
      label: "Description"
      helper_method: simple_format_values
    - field:
        - :contributor
        - :stored_searchable
      separator: "; "
      label: "Contributor"
      link_to_search: "Ddr::Index::Fields::CONTRIBUTOR_FACET"
    - field:
        - :product
        - :stored_searchable
      separator: "; "
      label: "Product"
      link_to_search: "Ddr::Index::Fields::PRODUCT_FACET"
    - field:
        - :category
        - :stored_searchable
      separator: "; "
      label: "Vehicle Category"
      link_to_search: "Ddr::Index::Fields::CATEGORY_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :setting
        - :stored_searchable
      separator: "; "
      label: "Setting"
      link_to_search: "Ddr::Index::Fields::SETTING_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :type
        - :stored_searchable
      separator: "; "
      label: "Type"
      link_to_search: "Ddr::Index::Fields::TYPE_FACET"
    - field:
        - :language_name
        - :stored_searchable
      separator: "; "
      label: "Language"
      link_to_search: "Ddr::Index::Fields::LANGUAGE_FACET"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: "Rights"
      helper_method: "rights_display"
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
      helper_method: :auto_link_values
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :box_number
        - :stored_searchable
      separator: "; "
      label: "Box Number"
      link_to_search: "Ddr::Index::Fields::BOX_NUMBER_FACET"
    - field:
        - :folder
        - :stored_searchable
      separator: "; "
      label: Folder
      link_to_search: "Ddr::Index::Fields::FOLDER_FACET"
    - field: "Ddr::Index::Fields::IDENTIFIER_ALL"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field: 'sponsor_display'
      separator: "; "
      label: "Sponsor"
      accessor: 'sponsor_display'
      helper_method: collection_sponsor

  add_index_field:
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :product
        - :stored_searchable
      separator: "; "
      label: "Product"
      link_to_search: "Ddr::Index::Fields::PRODUCT_FACET"
    - field:
        - :category
        - :stored_searchable
      separator: "; "
      label: "Vehicle Category"
      link_to_search: "Ddr::Index::Fields::CATEGORY_FACET"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
