includes:
  local_ids:
    - frankespada
showcase_images:
  local_ids:
    - espst001001
    - espst001002
    - espst001016
    - espst001022
  layout: landscape
highlight_images:
  local_ids:
    - espst001004
    - espst001010
    - espst001011
    - espst001012
    - espst001013
    - espst001019
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=frankespada
