includes:
  local_ids:
    - friedrichcarlpeetz
showcase_images:
  local_ids:
    - fcpst001001026
    - fcpst001001045
    - fcpst001001083
    - fcpst001001119
  layout: landscape
highlight_images:
  local_ids:
    - fcpst001001001
    - fcpst001001005
    - fcpst001001057
    - fcpst001001061
    - fcpst001001094
    - fcpst001001096
    - fcpst001001101
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=friedrichcarlpeetz
