collection_local_id:
  outdooradvertising:
    controller: digital_collections
    collection: outdooradvertising
    item_id_field: local_id
    thumbnail_image:
      custom_image: outdooradvertising-thumb-AAA8469c.jpg
