includes:
  local_ids:
    - outdooradvertising
showcase_images:
  local_ids:
    - AAA8469c
    - AAA7674
    - AAA7529
    - AAA6335
    - AAA6001
    - AAA4479
    - AAA2781
    - XXX1771
    - XXX2194
  layout: landscape
highlight_images:
  local_ids:
    - AAA8607
    - AAA2277
    - AAA7971
    - AAA0358
    - AAA8278b
    - AAA1762
    - AAA4086
    - AAA4497
    - AAA7458
    - AAA1645
    - AAA1351
    - AAA7337
    - AAA0050
    - AAA1979
    - AAA0618
    - AAA3028
    - AAA7325
    - AAA0629
    - AAA3284
    - AAA4888
    - AAA4981
    - AAA6763
    - XXH0891
    - XXX1497
    - XXH1454
    - XXX0663
    - XXX1324
    - XXX1816
    - XXX1936
    - XXX3068
    - XXX4230
    - XXX4264
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=outdooradvertising
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::COMPANY_FACET"
      label: Company
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::PLACEMENT_COMPANY_FACET"
      label: Placement Company
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::PRODUCT_FACET"
      label: Product
      collapse: false
      limit: 5
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::SPATIAL_FACET"
      label: Location
      limit: 5
    - field: "Ddr::Index::Fields::SETTING_FACET"
      label: Setting
      limit: 5
    - field: "Ddr::Index::Fields::MEDIUM_FACET"
      label: Medium
      limit: 5
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
    - field: "Ddr::Index::Fields::TONE_FACET"
      label: Tone
      limit: 5
    - field: "Ddr::Index::Fields::EAD_ID"
      label: "Source Collection"
      limit: 5
      helper_method: 'ead_id_title'
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::TYPE_FACET"
      label: Type
      show: false

  add_show_field:
    - field: "Ddr::Index::Fields::MEDIA_TYPE"
      label: "File"
      helper_method: file_info
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :headline
        - :stored_searchable
      label: "Headline"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :description
        - :stored_searchable
      label: "Description"
      helper_method: simple_format_values
    - field:
        - :company
        - :stored_searchable
      separator: "; "
      label: "Company"
      link_to_search: "Ddr::Index::Fields::COMPANY_FACET"
    - field:
        - :placement_company
        - :stored_searchable
      separator: "; "
      label: "Placement Company"
      link_to_search: "Ddr::Index::Fields::PLACEMENT_COMPANY_FACET"
    - field:
        - :product
        - :stored_searchable
      separator: "; "
      label: "Product"
      link_to_search: "Ddr::Index::Fields::PRODUCT_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :setting
        - :stored_searchable
      separator: "; "
      label: "Setting"
      link_to_search: "Ddr::Index::Fields::SETTING_FACET"
    - field:
        - :medium
        - :stored_searchable
      separator: "; "
      label: "Medium"
      link_to_search: "Ddr::Index::Fields::MEDIUM_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :type
        - :stored_searchable
      separator: "; "
      label: "Type"
      link_to_search: "Ddr::Index::Fields::TYPE_FACET"
    - field:
        - :tone
        - :stored_searchable
      separator: "; "
      label: "Tone"
      link_to_search: "Ddr::Index::Fields::TONE_FACET"
    - field:
        - :language_name
        - :stored_searchable
      separator: "; "
      label: "Language"
    - field:
        - :extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: "Rights"
      helper_method: "rights_display"
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
      helper_method: :auto_link_values
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field: "Ddr::Index::Fields::IDENTIFIER_ALL"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field: 'sponsor_display'
      separator: "; "
      label: "Sponsor"
      accessor: 'sponsor_display'
      helper_method: collection_sponsor

  add_index_field:
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :company
        - :stored_searchable
      separator: "; "
      label: "Company"
      link_to_search: "Ddr::Index::Fields::COMPANY_FACET"
    - field:
        - :product
        - :stored_searchable
      separator: "; "
      label: "Product"
      link_to_search: "Ddr::Index::Fields::PRODUCT_FACET"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
