includes:
  local_ids:
    - gedney

showcase_images:
  local_ids:
    - gedst008007009
  layout: landscape

highlight_images:
  local_ids:
    - gedst001011008
    - gedst001012004
    - gedst002002003
    - gedst002009007
    - gedst002010010
    - gedst003003009
    - gedst003004006
    - gedst003007002
    - gedst003009001
    - gedst005014006
    - gedst005014007
    - gedst005015001
    - gedst005015004
    - gedst005015008
    - gedst006003007
    - gedst006012007
    - gedst006014003
    - gedst007008008
    - gedst007009007
    - gedst007010001
    - gedst008003001
    - gedst008006005
    - gedst008007004
    - gedst008007006
    - gedst008007008
    - gedst008007009
    - gedst008009002
    - gedst008009005
    - gedst009001009
    - gedst009001011
    - gedst009002004
    - gedst009003002
    - gedst009004010
    - gedst009007003
    - gedst009008004
    - gedst009011002
    - gedst010004004
    - gedst010006002
    - gedst010006005
    - gedst012005002
    - gedst013004001
    - gedst013006002
    - gedst014006002
    - gedst016011001
    - gedst017006001
    - gedst017006006

restrictions:
  max_download: 1200
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=gedney

item_relators:
  - name: "Related Print"
    field:
      - :hasPart
      - :stored_searchable
    id_field:
      - :permanent_id
      - :stored_sortable
  - name: "Contact Sheet"
    field:
      - :isPartOf
      - :stored_searchable
    id_field:
      - :permanent_id
      - :stored_sortable

configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::SERIES_FACET"
      label: Series
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::SPATIAL_FACET"
      label: Location
      limit: 5
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::ASPACE_ID"
      label: ArchivesSpace ID
      show: false

  add_index_field:
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: "permalink"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"

  add_show_field:
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
    - field:
        - :series
        - :stored_searchable
      separator: "; "
      label: "Series"
      link_to_search: "Ddr::Index::Fields::SERIES_FACET"
    - field:
        - :description
        - :stored_searchable
      label: Description
    - field:
        - :spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field: "Ddr::Index::Fields::IDENTIFIER_ALL"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: "Rights"
      helper_method: "rights_display"
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
      helper_method: :auto_link_values
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field: 'sponsor_display'
      separator: "; "
      label: "Sponsor"
      accessor: 'sponsor_display'
      helper_method: collection_sponsor
