includes:
  local_ids:
    - kwilecki
showcase_images:
  local_ids:
    - kwlph030010270
    - kwlph040010500
    - kwlph050010060
    - kwlph060010020
    - kwlph090010450
    - kwlph110010140
  layout: landscape
highlight_images:
  local_ids:
    - kwlph010010010
    - kwlph010010290
    - kwlph020010170
    - kwlph030010530
    - kwlph040010160
    - kwlph040010400
    - kwlph060010220
    - kwlph060010320
    - kwlph070010140
    - kwlph070010170
    - kwlph080010060
    - kwlph090010370
    - kwlph100010550
    - kwlph110010390
restrictions:
  max_download: 1200
blog_posts: https://blogs.library.duke.edu/bitstreams/api/get_tag_posts/?tag_slug=kwilecki
configure_blacklight:
  add_facet_field:
    - field: "Ddr::Index::Fields::YEAR_FACET"
      label: Year
      limit: 9999
      collapse: false
      range:
        num_segments: 6
        segments: true
    - field: "Ddr::Index::Fields::FORMAT_FACET"
      label: Format
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::SUBJECT_FACET"
      label: Subject
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::SPATIAL_FACET"
      label: Location
      limit: 5
      collapse: false
    - field: "Ddr::Index::Fields::CREATOR_FACET"
      label: Creator
      limit: 5
    - field: "Ddr::Index::Fields::SERIES_FACET"
      label: Series
      limit: 5
    - field: "Ddr::Index::Fields::SUBSERIES_FACET"
      label: Subseries
      limit: 5
    - field: "Ddr::Index::Fields::ACTIVE_FEDORA_MODEL"
      label: Browse
      show: false
    - field: "Ddr::Index::Fields::BOX_NUMBER_FACET"
      label: "Box Number"
      show: false
    - field: "Ddr::Index::Fields::CONTRIBUTOR_FACET"
      label: Contributor
      limit: 5
      show: false
  add_index_field:
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: "permalink"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Collection"
      helper_method: "descendant_of"
    - field: "Ddr::Index::Fields::COLLECTION_URI"
      label: "Collection"
      helper_method: "descendant_of"
  add_show_field:
    - field: "Ddr::Index::Fields::MEDIA_TYPE"
      label: "File"
      helper_method: file_info
    - field: "Ddr::Index::Fields::TITLE"
      separator: "; "
      label: "Title"
    - field:
        - :date
        - :stored_searchable
      separator: "; "
      label: "Date"
      helper_method: display_edtf_date
    - field:
        - :creator
        - :stored_searchable
      separator: "; "
      label: "Creator"
      link_to_search: "Ddr::Index::Fields::CREATOR_FACET"
    - field:
        - :description
        - :stored_searchable
      label: Description
      helper_method: simple_format_values
    - field:
        - :spatial
        - :stored_searchable
      separator: "; "
      label: "Location"
      link_to_search: "Ddr::Index::Fields::SPATIAL_FACET"
    - field:
        - :subject
        - :stored_searchable
      separator: "; "
      label: "Subject"
      link_to_search: "Ddr::Index::Fields::SUBJECT_FACET"
    - field:
        - :format
        - :stored_searchable
      separator: "; "
      label: "Format"
      link_to_search: "Ddr::Index::Fields::FORMAT_FACET"
    - field:
        - :language_name
        - :stored_searchable
      separator: "; "
      label: "Language"
    - field:
        - :extent
        - :stored_searchable
      separator: "; "
      label: "Extent"
    - field: "Ddr::Index::Fields::IS_PART_OF"
      label: "Part of"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::IS_MEMBER_OF_COLLECTION"
      label: "Digital Collection"
      helper_method: descendant_of
    - field: "Ddr::Index::Fields::EAD_ID"
      separator: "; "
      label: "Source Collection"
      helper_method: source_collection
    - field:
        - :series
        - :stored_searchable
      separator: "; "
      label: "Series"
      link_to_search: "Ddr::Index::Fields::SERIES_FACET"
    - field:
        - :subseries
        - :stored_searchable
      separator: "; "
      label: "Subseries"
      link_to_search: "Ddr::Index::Fields::SUBSERIES_FACET"
    - field:
        - :box_number
        - :stored_searchable
      separator: "; "
      label: "Box Number"
      link_to_search: "Ddr::Index::Fields::BOX_NUMBER_FACET"
    - field:
        - :folder
        - :stored_searchable
      separator: "; "
      label: "Folder"
    - field:
        - :print_number
        - :stored_searchable
      separator: "; "
      label: "Print Number"
    - field:
        - :provenance
        - :stored_searchable
      separator: "; "
      label: "Provenance"
      helper_method: :auto_link_values
    - field:
        - :rights
        - :stored_searchable
      separator: "; "
      label: "Rights"
      helper_method: "rights_display"
    - field:
        - :rights_note
        - :stored_searchable
      separator: "; "
      label: "Rights Note"
      helper_method: :auto_link_values
    - field: "Ddr::Index::Fields::IDENTIFIER_ALL"
      separator: "; "
      label: "Identifier"
    - field: "Ddr::Index::Fields::PERMANENT_URL"
      label: "Permalink"
      helper_method: permalink
    - field:
        - :bibliographicCitation
        - :stored_searchable
      separator: "; "
      label: "Citation"
    - field: 'sponsor_display'
      separator: "; "
      label: "Sponsor"
      accessor: 'sponsor_display'
      helper_method: collection_sponsor
